name = input("What is your name : ")
last_name = input("What is your surname : ")
age = input("How old are you : ")
mothers_name = input("Whats your mothers name : ")
fathers_name = input("Whats your fathers name : ")
address = input("Where do you live at? : ")
hobby = input("Whats your hobby? : ")

print(name)
print(last_name)
print(age)
print(mothers_name)
print(fathers_name)
print(address)
print(hobby)